In [47]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
from sklearn.metrics import classification_report

In [97]:
dataset = pd.read_csv('Dataset/italy/tes_itali.csv', encoding= 'unicode_escape')
dataset.head()

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,Chievo,Juventus,7.0,23.0,2.0,11.0,0.0,8.0,7.0,9.0,2.0,0.0,0.0,0.0,1.0,1.0,A
1,Lazio,Napoli,9.0,11.0,5.0,6.0,4.0,7.0,8.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0,A
2,Bologna,Spal,8.0,10.0,3.0,5.0,7.0,0.0,16.0,11.0,4.0,2.0,1.0,0.0,0.0,0.0,A
3,Empoli,Cagliari,9.0,12.0,4.0,5.0,6.0,6.0,19.0,19.0,3.0,3.0,0.0,0.0,1.0,0.0,H
4,Parma,Udinese,9.0,16.0,6.0,6.0,4.0,5.0,10.0,13.0,2.0,2.0,0.0,0.0,1.0,0.0,D

In [98]:
rata2=dataset['HF'].mean()
dataset['HF']=dataset['HF'].fillna(rata2)
rata2=dataset['AF'].mean()
dataset['AF']=dataset['AF'].fillna(rata2)
dataset

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,Chievo,Juventus,7.0,23.0,2.0,11.0,0.0,8.0,7.0,9.0,2.0,0.0,0.0,0.0,1.0,1.0,A
1,Lazio,Napoli,9.0,11.0,5.0,6.0,4.0,7.0,8.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0,A
2,Bologna,Spal,8.0,10.0,3.0,5.0,7.0,0.0,16.0,11.0,4.0,2.0,1.0,0.0,0.0,0.0,A
3,Empoli,Cagliari,9.0,12.0,4.0,5.0,6.0,6.0,19.0,19.0,3.0,3.0,0.0,0.0,1.0,0.0,H
4,Parma,Udinese,9.0,16.0,6.0,6.0,4.0,5.0,10.0,13.0,2.0,2.0,0.0,0.0,1.0,0.0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Como,Cremonese,14.0,13.0,3.0,3.0,5.0,6.0,11.0,18.0,3.0,1.0,0.0,0.0,0.0,1.0,A
2996,Cosenza,Cittadella,11.0,8.0,4.0,2.0,4.0,3.0,4.0,10.0,1.0,2.0,0.0,0.0,0.0,0.0,H
2997,Frosinone,Pisa,14.0,6.0,1.0,3.0,6.0,3.0,14.0,17.0,4.0,3.0,0.0,0.0,0.0,2.0,A
2998,Lecce,Pordenone,24.0,2.0,7.0,0.0,7.0,1.0,12.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,H
2999,Perugia,Monza,21.0,20.0,7.0,7.0,10.0,5.0,15.0,15.0,3.0,3.0,0.0,0.0,0.0,0.0,H

In [103]:
import random
le=LabelEncoder()
dataset['HomeTeam']=le.fit_transform(-dataset['HomeTeam'])
dataset['AwayTeam']=le.fit_transform(-dataset['AwayTeam'])
dataset['FTR']=le.fit_transform(dataset['FTR'])
#sorted_indices = np.argsort(-dataset['HomeTeam'])
#sorted_data = le.inverse_transform(dataset['AwayTeam'][sorted_indices])
dataset

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,42,29,7.0,23.0,2.0,11.0,0.0,8.0,7.0,9.0,2.0,0.0,0.0,0.0,1.0,1.0,0
1,28,23,9.0,11.0,5.0,6.0,4.0,7.0,8.0,5.0,0.0,0.0,0.0,0.0,1.0,1.0,0
2,46,9,8.0,10.0,3.0,5.0,7.0,0.0,16.0,11.0,4.0,2.0,1.0,0.0,0.0,0.0,0
3,36,44,9.0,12.0,4.0,5.0,6.0,6.0,19.0,19.0,3.0,3.0,0.0,0.0,1.0,0.0,2
4,20,4,9.0,16.0,6.0,6.0,4.0,5.0,10.0,13.0,2.0,2.0,0.0,0.0,1.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,40,38,14.0,13.0,3.0,3.0,5.0,6.0,11.0,18.0,3.0,1.0,0.0,0.0,0.0,1.0,0
2996,39,41,11.0,8.0,4.0,2.0,4.0,3.0,4.0,10.0,1.0,2.0,0.0,0.0,0.0,0.0,2
2997,33,17,14.0,6.0,1.0,3.0,6.0,3.0,14.0,17.0,4.0,3.0,0.0,0.0,0.0,2.0,0
2998,27,16,24.0,2.0,7.0,0.0,7.0,1.0,12.0,6.0,3.0,0.0,0.0,0.0,0.0,0.0,2
2999,19,24,21.0,20.0,7.0,7.0,10.0,5.0,15.0,15.0,3.0,3.0,0.0,0.0,0.0,0.0,2

In [51]:
#import random
#encoded_data = le.fit_transform(dataset['HomeTeam'])
# Mengacak angka dalam encoded_data
#random.shuffle(encoded_data)

# Mengembalikan ke bentuk aslinya
#decoded_data = le.inverse_transform(encoded_data)
#dataset

In [104]:
X = dataset[dataset.columns[0:16]]
Y = dataset['FTR']

In [105]:
 # membagi dataset menjadi training dan testing 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [106]:
grGermany = xgb.XGBClassifier(random_state=10)
grGermany.fit(X_train, y_train)
grGermany_pred = grGermany.predict(X_test)
print("pred", grGermany_pred)  #hasil prediksi 
print("tes", y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, grGermany_pred)*100)

pred [0 2 2 2 1 2 0 2 0 1 2 2 2 0 2 2 2 0 1 1 2 2 0 2 1 1 1 2 1 2 0 1 2 1 2 2 2
 1 2 2 2 2 2 2 2 2 0 2 2 1 1 2 2 2 2 1 2 0 1 0 0 2 2 2 2 0 1 2 0 1 1 0 0 2
 1 1 1 2 2 1 2 1 1 2 0 2 0 0 2 0 2 2 2 0 2 0 2 2 0 2 1 2 2 1 0 0 2 1 2 2 1
 1 0 2 2 2 0 0 2 1 1 2 2 2 2 2 2 1 1 0 2 0 1 2 0 2 2 0 2 0 0 0 1 0 1 2 2 0
 0 1 2 1 2 2 2 2 0 0 2 1 1 1 1 1 0 2 1 2 2 1 2 1 1 2 2 2 2 2 2 2 2 2 2 1 2
 0 1 0 0 2 2 1 2 0 2 2 0 1 2 1 0 0 1 0 2 2 2 1 1 0 0 2 2 2 0 2 2 2 0 2 2 0
 2 2 0 2 2 0 2 0 1 0 1 2 0 1 2 0 1 1 2 1 1 0 1 0 1 2 1 2 2 0 2 2 2 0 0 1 0
 2 2 0 0 0 2 0 1 2 1 0 2 0 0 2 2 0 2 0 1 2 2 0 0 2 2 1 2 0 2 0 0 1 1 2 2 2
 2 2 0 0 0 0 1 1 2 2 2 0 0 1 0 0 0 0 0 0 2 1 1 1 2 2 0 2 0 2 2 1 0 2 2 1 1
 0 2 2 1 0 2 1 1 2 0 2 0 1 2 1 0 2 2 2 1 0 0 0 1 2 1 2 2 1 2 2 2 0 0 1 1 2
 2 0 2 0 0 0 2 0 2 1 0 2 2 2 2 0 1 1 0 2 2 2 0 0 2 1 2 1 2 0 0 1 1 2 0 2 0
 1 2 2 1 0 0 1 0 2 0 0 0 0 2 0 2 1 2 2 2 0 1 0 2 0 2 1 2 1 0 1 2 1 1 2 2 2
 1 2 1 1 0 1 0 0 0 2 0 2 0 0 2 1 0 0 2 1 1 2 1 2 1 1 1 1 1 0 1 2 2 2 2 0 0
 1 1 2 1 0 2 0 2 0 2 2 2 0 2 0 0 0 2 0 0 0 1 2 0 2 2 2 0 1 0 2 2 0 2 1 0 2
 2 0 0 2 0 2 0 2 2 1 2 0 2 2 2 2 2 2 0 0 0 2 2 2 1 2 2 2 1 1 0 2 0 1 1 0 2
 2 0 1 1 0 2 2 2 2 1 0 2 0 0 0 2 2 0 0 2 2 2 1 0 1 0 0 0 1 2 0 2 0 2 2 2 1
 1 2 1 2 2 0 2 2]
tes 1957    0
2087    2
1394    2
1520    1
1098    2
       ..
2495    0
94      2
2742    0
1999    2
1178    1
Name: FTR, Length: 600, dtype: int64
58.5

In [108]:
lgbFrance = lgb.LGBMClassifier(random_state=10)
lgbFrance.fit(X_train, y_train)
lgbFrance_pred = lgbFrance.predict(X_test)
print(lgbFrance_pred)  #hasil prediksi 
print(y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, lgbFrance_pred)*100)

[0 2 2 2 1 2 0 2 0 1 0 2 1 1 2 2 2 1 1 1 2 2 0 2 1 0 1 2 1 2 0 1 2 1 2 2 2
 0 2 2 2 2 2 2 2 2 0 2 2 0 1 2 2 2 2 1 2 0 2 2 0 2 2 2 1 0 1 2 2 0 2 0 0 1
 1 2 1 2 2 1 2 1 1 2 0 2 0 2 2 0 2 2 2 0 2 0 2 2 0 2 1 1 2 1 0 0 2 0 2 2 1
 1 0 2 2 2 0 0 1 1 1 1 2 2 2 2 0 1 0 0 2 0 1 1 0 2 2 0 2 0 0 1 0 0 1 2 2 0
 2 1 2 2 0 2 2 2 0 0 2 2 1 1 0 0 2 2 1 2 2 1 2 0 1 2 2 2 2 2 2 2 2 2 2 1 2
 0 1 0 0 1 2 1 2 0 2 2 0 1 2 1 0 0 1 0 2 2 2 2 1 0 0 2 2 2 0 2 2 2 0 2 2 0
 2 2 2 2 2 1 2 0 1 0 2 1 1 0 2 0 1 1 2 1 1 0 1 2 1 2 1 1 2 0 2 1 2 0 0 2 0
 2 2 1 1 0 2 0 1 2 1 0 2 0 0 2 2 0 2 1 1 2 2 0 0 2 0 1 2 0 2 0 0 1 1 2 2 2
 2 2 0 0 0 0 1 1 2 2 2 0 0 1 0 0 0 0 0 0 2 1 0 1 2 2 0 2 0 2 2 1 0 2 2 1 1
 0 2 2 1 0 2 2 0 2 0 2 0 2 2 2 0 2 0 2 1 1 0 0 1 2 1 2 2 1 2 2 2 0 0 1 1 2
 2 1 2 0 0 0 2 0 2 1 0 2 2 2 2 0 1 0 0 2 2 2 0 0 2 2 2 0 2 0 0 1 1 2 0 2 0
 2 2 2 1 0 0 1 0 1 0 0 0 1 2 0 1 1 2 0 2 0 1 0 2 0 2 1 1 0 0 1 2 1 1 2 2 2
 0 1 1 2 0 1 0 1 2 2 0 2 0 0 2 1 0 0 1 1 1 0 1 2 1 0 1 1 2 0 1 2 2 2 0 0 0
 0 2 1 1 0 2 0 2 0 2 2 2 0 2 0 0 0 2 0 0 0 1 2 0 2 2 2 0 2 0 2 2 0 2 1 0 1
 2 0 0 2 0 2 0 2 2 1 2 0 2 2 2 2 2 2 0 0 0 2 1 2 1 2 2 2 2 1 0 2 1 1 1 0 2
 2 0 1 1 0 2 2 2 2 1 0 2 1 2 0 2 2 0 1 2 2 1 1 0 1 0 0 0 1 2 0 2 1 2 2 2 1
 1 2 1 2 2 0 2 2]
1957    0
2087    2
1394    2
1520    1
1098    2
       ..
2495    0
94      2
2742    0
1999    2
1178    1
Name: FTR, Length: 600, dtype: int64
59.5

In [109]:
abFrance = AdaBoostClassifier(random_state=10, learning_rate=0.20)
abFrance.fit(X_train, y_train)
abFrance_pred = abFrance.predict(X_test)
print(abFrance_pred)  #hasil prediksi 
print(y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, abFrance_pred)*100)

[0 2 2 2 2 0 0 2 0 0 0 2 1 1 2 2 2 1 1 2 2 2 0 2 1 0 1 2 2 2 0 1 2 1 2 2 2
 0 2 2 2 2 2 2 2 2 0 2 2 0 2 2 2 2 2 1 0 0 2 0 0 1 2 1 1 0 1 2 2 1 2 0 0 1
 1 2 1 2 2 2 2 1 0 2 0 2 0 2 2 0 2 2 2 0 2 0 2 2 0 2 1 1 2 2 2 0 2 0 2 2 2
 1 0 2 2 2 1 0 1 1 0 2 2 2 2 2 0 2 0 0 2 0 1 1 0 1 2 0 2 0 0 1 0 1 1 2 2 0
 2 2 2 2 2 2 2 1 1 1 2 1 1 2 0 1 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 0 2
 0 1 0 2 1 2 2 2 0 1 2 0 0 2 1 1 0 2 1 2 2 2 1 2 0 0 2 2 2 1 2 2 2 1 2 2 0
 2 2 2 2 2 0 2 0 1 0 1 0 0 2 2 0 0 1 2 1 2 0 2 2 2 1 1 0 1 0 2 1 2 0 0 1 2
 2 2 1 0 0 2 0 2 2 1 0 2 0 0 2 0 0 2 0 2 1 1 0 1 2 0 0 1 0 2 1 0 1 1 2 2 2
 2 2 0 0 0 0 1 2 2 2 2 0 0 1 0 0 0 0 0 0 2 2 0 0 2 2 0 1 0 1 1 2 0 2 2 1 1
 0 2 2 2 0 2 2 0 2 0 2 0 1 2 2 0 2 1 2 1 0 0 0 1 2 0 2 2 0 2 2 2 0 0 2 1 1
 2 0 1 0 1 0 2 0 2 2 0 2 2 2 1 0 2 0 0 2 2 2 1 0 2 1 2 0 2 0 0 2 0 1 0 2 0
 2 2 2 1 0 0 1 2 1 1 0 0 0 1 0 0 1 2 0 2 0 1 0 2 0 2 1 2 1 0 1 2 2 2 2 2 2
 0 2 0 1 0 1 0 1 1 2 0 2 0 0 2 2 0 0 2 1 1 2 0 2 1 0 0 1 2 0 0 2 2 2 1 0 0
 0 1 2 2 0 2 1 2 0 1 2 2 0 2 0 0 0 2 0 0 0 2 2 0 2 2 2 0 1 0 2 2 0 2 1 0 2
 2 0 1 2 0 2 0 2 2 2 2 0 1 2 2 1 2 2 0 0 0 2 2 2 2 2 2 0 2 1 0 2 0 0 1 0 2
 2 0 1 2 0 2 0 2 2 1 0 1 0 2 0 2 2 0 1 2 2 2 2 0 2 0 0 0 1 2 0 2 0 2 2 2 0
 1 2 2 2 2 0 2 2]
1957    0
2087    2
1394    2
1520    1
1098    2
       ..
2495    0
94      2
2742    0
1999    2
1178    1
Name: FTR, Length: 600, dtype: int64
64.83333333333333