In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import xgboost as xgb
import lightgbm as lgb
from sklearn.ensemble import AdaBoostClassifier
from sklearn import metrics
from sklearn.metrics import classification_report

In [18]:
dataset = pd.read_csv('Dataset/france/tes_france.csv', encoding= 'unicode_escape')
dataset.head()

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,Marseille,Toulouse,23.0,5.0,10.0,1.0,5.0,1.0,7.0,20.0,1.0,3.0,0.0,0.0,1.0,0.0,H
1,Angers,Nimes,21.0,14.0,7.0,5.0,5.0,1.0,20.0,12.0,2.0,2.0,0.0,1.0,1.0,1.0,A
2,Lille,Rennes,15.0,8.0,6.0,2.0,2.0,6.0,12.0,13.0,1.0,0.0,0.0,0.0,1.0,1.0,H
3,Montpellier,Dijon,16.0,9.0,7.0,4.0,4.0,2.0,15.0,21.0,2.0,2.0,0.0,0.0,1.0,0.0,A
4,Nantes,Monaco,16.0,11.0,4.0,6.0,7.0,2.0,8.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,A

In [4]:
#rata2=df['HF'].mean()
#df['HF']=df['HF'].fillna(rata2)
#rata2=df['AF'].mean()
#df['AF']=df['AF'].fillna(rata2)
#df

In [23]:
import random
le=LabelEncoder()
dataset['HomeTeam']=le.fit_transform(dataset['HomeTeam'])
dataset['AwayTeam']=le.fit_transform(dataset['AwayTeam'])
dataset['FTR']=le.fit_transform(dataset['FTR'])
dataset

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,34,44,23.0,5.0,10.0,1.0,5.0,1.0,7.0,20.0,1.0,3.0,0.0,0.0,1.0,0.0,2
1,31,30,21.0,14.0,7.0,5.0,5.0,1.0,20.0,12.0,2.0,2.0,0.0,1.0,1.0,1.0,0
2,29,39,15.0,8.0,6.0,2.0,2.0,6.0,12.0,13.0,1.0,0.0,0.0,0.0,1.0,1.0,2
3,9,13,16.0,9.0,7.0,4.0,4.0,2.0,15.0,21.0,2.0,2.0,0.0,0.0,1.0,0.0,0
4,11,25,16.0,11.0,4.0,6.0,7.0,2.0,8.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2832,23,46,8.0,9.0,2.0,4.0,4.0,3.0,9.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0
2833,17,15,14.0,8.0,4.0,4.0,4.0,4.0,8.0,11.0,0.0,3.0,0.0,0.0,0.0,0.0,2
2834,44,14,13.0,4.0,5.0,3.0,2.0,4.0,13.0,12.0,1.0,1.0,0.0,0.0,1.0,1.0,2
2835,23,9,9.0,10.0,3.0,5.0,9.0,4.0,8.0,6.0,1.0,1.0,0.0,0.0,0.0,0.0,2
2836,24,13,15.0,9.0,9.0,2.0,7.0,2.0,4.0,5.0,0.0,1.0,0.0,0.0,1.0,0.0,1

In [26]:
random.shuffle(dataset['HomeTeam'])
random.shuffle(dataset['AwayTeam'])
dataset

c:\Users\asus\anaconda3\lib\random.py:394: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i], x[j] = x[j], x[i]

,HomeTeam,AwayTeam,HS,AS,HST,AST,HC,AC,HF,AF,HY,AY,HR,AR,HTHG,HTAG,FTR
0,27,29,23.0,5.0,10.0,1.0,5.0,1.0,7.0,20.0,1.0,3.0,0.0,0.0,1.0,0.0,2
1,26,4,21.0,14.0,7.0,5.0,5.0,1.0,20.0,12.0,2.0,2.0,0.0,1.0,1.0,1.0,0
2,17,21,15.0,8.0,6.0,2.0,2.0,6.0,12.0,13.0,1.0,0.0,0.0,0.0,1.0,1.0,2
3,33,13,16.0,9.0,7.0,4.0,4.0,2.0,15.0,21.0,2.0,2.0,0.0,0.0,1.0,0.0,0
4,20,16,16.0,11.0,4.0,6.0,7.0,2.0,8.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2832,33,24,8.0,9.0,2.0,4.0,4.0,3.0,9.0,14.0,0.0,0.0,0.0,0.0,1.0,1.0,0
2833,25,38,14.0,8.0,4.0,4.0,4.0,4.0,8.0,11.0,0.0,3.0,0.0,0.0,0.0,0.0,2
2834,1,19,13.0,4.0,5.0,3.0,2.0,4.0,13.0,12.0,1.0,1.0,0.0,0.0,1.0,1.0,2
2835,28,41,9.0,10.0,3.0,5.0,9.0,4.0,8.0,6.0,1.0,1.0,0.0,0.0,0.0,0.0,2
2836,3,45,15.0,9.0,9.0,2.0,7.0,2.0,4.0,5.0,0.0,1.0,0.0,0.0,1.0,0.0,1

In [27]:
#import random
#encoded_data = le.fit_transform(dataset['HomeTeam'])
# Mengacak angka dalam encoded_data
#random.shuffle(encoded_data)

# Mengembalikan ke bentuk aslinya
#decoded_data = le.inverse_transform(encoded_data)
#dataset

In [28]:
X = dataset[dataset.columns[0:16]]
Y = dataset['FTR']

In [29]:
 # membagi dataset menjadi training dan testing 
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [30]:
grGermany = xgb.XGBClassifier(random_state=10)
grGermany.fit(X_train, y_train)
grGermany_pred = grGermany.predict(X_test)
print("pred", grGermany_pred)  #hasil prediksi 
print("tes", y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, grGermany_pred)*100)

pred [2 2 2 1 2 1 2 2 1 2 0 2 1 2 1 0 2 1 2 1 2 2 0 2 1 2 1 2 0 2 2 0 2 1 0 0 2
 2 2 1 1 2 0 0 1 2 0 1 0 0 0 1 0 0 2 2 1 2 2 2 2 0 1 2 1 1 0 2 1 1 0 1 1 0
 2 0 2 1 2 2 1 0 1 1 2 1 1 0 2 1 1 2 0 0 2 0 2 2 2 0 1 1 2 2 1 1 0 1 0 0 2
 1 1 0 2 2 2 1 2 1 1 2 2 1 1 0 2 1 2 0 2 2 2 2 2 2 2 0 2 1 1 0 0 0 0 2 2 0
 0 0 1 2 0 0 2 2 2 1 1 2 0 2 2 1 2 0 2 1 0 0 2 0 2 0 0 2 1 1 2 2 2 0 0 0 2
 1 2 0 2 2 2 1 2 0 2 0 2 1 1 1 1 1 1 2 0 2 2 2 2 2 0 1 2 0 2 1 1 0 2 1 0 1
 1 1 2 2 0 2 0 0 0 2 1 2 0 0 1 2 2 0 2 2 1 1 0 2 1 2 2 0 2 1 2 1 1 1 2 0 2
 2 0 0 2 0 2 1 0 2 2 1 2 0 2 2 2 1 2 2 2 0 1 2 2 2 0 2 2 0 0 2 1 1 2 2 0 0
 2 1 2 2 0 2 0 1 2 1 2 1 2 2 0 1 1 1 2 2 2 2 0 0 2 0 1 1 2 0 1 0 2 0 1 2 0
 1 2 2 0 0 0 2 2 2 0 2 2 0 1 1 0 1 2 2 0 1 0 2 2 2 1 2 2 0 1 2 1 0 0 2 0 0
 1 1 0 1 1 1 2 1 1 2 0 2 0 0 2 1 0 1 1 1 1 2 0 2 2 0 1 2 1 2 0 2 2 0 1 2 1
 1 2 0 0 2 2 2 2 2 1 2 1 2 2 1 0 2 2 2 0 2 2 2 0 1 0 2 2 2 2 2 2 2 2 1 0 1
 0 2 2 0 2 1 2 0 0 1 2 2 2 0 0 2 2 0 2 1 2 2 2 1 1 2 2 0 2 0 1 2 1 2 2 1 2
 1 2 1 1 2 0 1 1 1 2 2 0 1 1 2 2 1 2 1 1 0 2 1 1 1 2 0 2 1 2 1 1 2 1 0 2 2
 2 2 2 0 0 0 1 1 2 2 0 2 0 2 0 2 0 2 2 0 2 2 0 2 1 2 0 1 0 1 0 2 0 1 2 1 2
 1 0 0 1 2 2 0 1 2 2 2 0 1]
tes 2692    0
1126    2
959     2
1592    0
2399    2
       ..
208     2
2375    2
1406    0
2174    0
425     1
Name: FTR, Length: 568, dtype: int64
55.1056338028169

In [31]:
lgbFrance = lgb.LGBMClassifier(random_state=10)
lgbFrance.fit(X_train, y_train)
lgbFrance_pred = lgbFrance.predict(X_test)
print(lgbFrance_pred)  #hasil prediksi 
print(y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, lgbFrance_pred)*100)

[2 2 2 1 2 0 2 2 1 2 0 2 1 2 1 0 2 1 2 1 2 2 0 2 2 2 1 2 0 2 2 0 2 2 0 0 2
 2 2 1 1 2 0 0 2 2 0 1 0 0 0 2 0 0 0 2 1 2 2 2 2 0 1 2 1 1 0 0 1 1 0 1 1 0
 2 0 2 2 2 2 2 0 1 1 2 1 0 0 2 1 1 2 0 0 2 0 2 2 2 0 1 1 2 1 0 1 1 1 0 0 2
 1 1 0 2 2 2 1 2 1 1 2 1 1 1 0 2 2 2 0 2 2 2 2 2 2 2 0 2 1 1 0 0 0 0 2 2 0
 0 0 1 2 0 0 2 2 2 1 0 2 0 2 2 1 2 0 2 1 0 2 2 0 2 0 0 2 1 1 2 0 1 1 1 0 2
 1 2 0 2 2 2 2 2 0 2 2 1 1 2 1 1 1 1 2 0 2 2 2 2 2 0 2 2 0 2 1 1 0 2 1 0 1
 1 1 2 2 0 2 0 0 0 2 1 2 0 0 1 2 2 0 2 2 1 1 0 2 1 2 2 0 2 1 0 0 1 1 1 0 2
 2 0 0 2 1 2 1 0 2 2 1 2 0 1 1 2 2 2 2 2 0 0 2 2 2 0 2 1 1 1 2 1 0 2 1 0 1
 2 2 2 2 0 2 0 2 2 1 2 0 2 2 0 1 1 1 2 2 2 2 0 0 2 0 0 2 2 0 1 1 2 0 1 2 0
 1 1 0 0 0 0 2 2 1 0 2 2 0 1 1 0 1 2 1 0 0 0 2 2 2 1 2 2 0 2 1 1 0 0 2 0 0
 1 1 0 1 1 2 2 1 1 2 0 2 0 0 2 1 0 1 1 1 1 2 0 2 2 0 1 2 1 2 0 1 0 0 0 2 1
 1 2 0 0 2 2 2 2 2 1 2 1 2 2 1 0 2 2 2 0 2 2 2 0 2 0 2 2 2 2 2 2 1 1 1 0 1
 0 2 0 1 2 1 2 0 0 1 2 2 2 2 0 2 2 2 2 1 2 2 2 1 1 2 2 0 2 0 1 2 1 2 2 0 2
 1 2 0 1 2 0 0 1 1 2 2 0 1 1 2 2 1 2 1 2 0 2 1 1 2 2 0 2 1 2 1 1 2 1 0 2 2
 2 2 2 0 0 0 1 0 2 2 0 2 0 2 0 2 0 2 2 0 2 2 0 2 2 2 0 1 0 1 0 2 0 1 2 1 2
 2 0 0 1 2 2 0 2 2 2 2 0 1]
2692    0
1126    2
959     2
1592    0
2399    2
       ..
208     2
2375    2
1406    0
2174    0
425     1
Name: FTR, Length: 568, dtype: int64
58.97887323943662

In [32]:
abFrance = AdaBoostClassifier(random_state=10, learning_rate=0.20)
abFrance.fit(X_train, y_train)
abFrance_pred = abFrance.predict(X_test)
print(abFrance_pred)  #hasil prediksi 
print(y_test)  #jawaban yang sebenarnya
print(metrics.accuracy_score(y_test, abFrance_pred)*100)

[1 2 2 1 2 0 1 2 1 2 0 2 2 2 2 0 1 2 2 1 2 2 0 2 2 2 2 2 1 2 2 0 2 1 0 0 2
 2 2 1 1 2 0 0 2 2 1 2 0 0 0 1 0 0 2 2 2 2 2 2 2 1 1 2 1 1 1 1 1 1 0 0 1 1
 2 0 2 2 1 2 2 0 1 0 2 1 1 1 2 0 1 2 0 0 2 0 2 2 2 0 2 0 2 2 2 1 2 0 0 2 2
 1 1 0 2 2 2 1 2 0 2 1 2 1 1 0 2 2 2 0 2 2 2 1 2 2 2 1 2 1 1 1 1 1 0 2 2 1
 0 0 1 2 0 2 2 2 2 2 0 2 2 1 2 0 2 1 2 0 0 2 2 0 2 0 2 0 1 0 2 0 2 0 2 1 2
 1 2 0 2 2 2 2 2 1 2 0 0 0 2 2 2 2 1 2 1 2 2 1 2 2 0 2 2 0 2 2 1 0 2 1 0 1
 1 0 2 2 0 2 0 1 0 2 1 2 0 0 1 1 2 1 2 2 1 1 0 2 1 1 2 0 2 1 1 1 1 1 1 1 2
 2 0 1 2 0 2 1 0 2 2 1 2 1 2 1 2 2 2 2 2 0 1 2 2 2 0 1 2 1 1 2 2 0 2 2 0 1
 2 2 1 0 2 2 0 2 2 0 2 1 0 2 0 1 2 1 1 2 2 2 0 0 2 0 0 2 2 1 2 1 2 0 0 2 0
 1 1 1 0 0 0 1 1 1 0 2 2 1 0 1 1 1 2 2 0 1 0 2 2 2 0 2 2 0 2 1 2 0 0 2 0 0
 2 2 0 1 1 1 2 1 1 2 0 2 1 0 2 1 0 1 1 2 2 2 0 2 1 0 1 2 2 2 0 1 2 0 1 2 1
 0 2 0 1 2 2 2 1 2 0 2 2 2 2 1 1 2 2 2 0 2 2 1 0 1 0 2 2 2 2 2 2 1 1 2 0 1
 0 2 0 0 2 1 2 0 0 2 2 2 2 2 0 2 0 2 1 1 2 2 2 1 2 2 2 1 2 0 1 2 1 2 2 1 2
 1 2 0 2 2 0 0 0 1 2 2 0 2 1 2 2 1 2 1 0 0 2 1 2 2 0 0 2 0 2 1 2 2 1 0 2 2
 2 2 2 0 0 0 2 1 2 2 0 2 0 2 0 1 0 2 2 0 2 2 0 2 1 1 0 1 0 2 0 2 0 2 2 0 1
 2 0 0 0 2 2 0 1 2 2 2 0 1]
2692    0
1126    2
959     2
1592    0
2399    2
       ..
208     2
2375    2
1406    0
2174    0
425     1
Name: FTR, Length: 568, dtype: int64
59.33098591549296